# Here we must undersand the data that we have!

In [1]:
import pandas as pd
import requests

api = "https://api.carrismetropolitana.pt/v2"

In [2]:
# oeiras train station, lots of lines stop here
stop_id = "121270"

r = requests.get(f"{api}/arrivals/by_stop/{stop_id}")
df = pd.DataFrame(r.json())

In [3]:
df.head(5)

,estimated_arrival,estimated_arrival_unix,headsign,line_id,observed_arrival,observed_arrival_unix,pattern_id,related_trip_ids,route_id,scheduled_arrival,scheduled_arrival_unix,stop_sequence,trip_id,vehicle_id
0,None,NaN,Carcavelos (Estação),1604,None,None,[LA77N]1604_0_3,None,[LA77N]1604_0,05:56:00,1790571360,14,None,None
1,None,NaN,Oeiras (Estação Norte),1523,None,None,[LA77N]1523_0_1,None,[LA77N]1523_0,06:02:00,1790571720,37,None,None
2,None,NaN,Portela de Sintra (Estação Sul),1618,None,None,[LA77N]1618_0_1,None,[LA77N]1618_0,06:05:00,1790571900,6,None,None
3,None,NaN,Oeiras (Estação Norte),1523,None,None,[LA77N]1523_0_1,None,[LA77N]1523_0,06:07:00,1790572020,37,None,None
4,None,NaN,Agualva-Cacém (Estação),1523,None,None,[LA77N]1523_0_2,None,[LA77N]1523_0,06:10:00,1790572200,1,None,None

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   estimated_arrival       12 non-null     object
 1   estimated_arrival_unix  12 non-null     float64
 2   headsign                332 non-null    object
 3   line_id                 332 non-null    object
 4   observed_arrival        0 non-null      object
 5   observed_arrival_unix   0 non-null      object
 6   pattern_id              332 non-null    object
 7   related_trip_ids        0 non-null      object
 8   route_id                332 non-null    object
 9   scheduled_arrival       332 non-null    object
 10  scheduled_arrival_unix  332 non-null    int64
 11  stop_sequence           332 non-null    int64
 12  trip_id                 12 non-null     object
 13  vehicle_id              12 non-null     object
dtypes: float64(1), int64(2), object(11)
memory usage: 36.4+ KB

In [5]:
df.shape  # this means that we have a lot of features without information at all

(332, 14)

In [6]:
# how many empty values per column
df.isna().sum()

estimated_arrival         320
estimated_arrival_unix    320
headsign                    0
line_id                     0
observed_arrival          332
observed_arrival_unix     332
pattern_id                  0
related_trip_ids          332
route_id                    0
scheduled_arrival           0
scheduled_arrival_unix      0
stop_sequence               0
trip_id                   320
vehicle_id                320
dtype: int64

In [7]:
# how many different values per column
df.nunique()

estimated_arrival          12
estimated_arrival_unix     12
headsign                    9
line_id                     9
observed_arrival            0
observed_arrival_unix       0
pattern_id                 12
related_trip_ids            0
route_id                   10
scheduled_arrival         297
scheduled_arrival_unix    297
stop_sequence              10
trip_id                    12
vehicle_id                 11
dtype: int64

In [8]:
# the 4 rows that have live info, next to the time right now
from datetime import datetime
print(datetime.now())

live = df[df["estimated_arrival"].notna()]
live[["line_id", "scheduled_arrival", "estimated_arrival", "trip_id", "vehicle_id"]]

2026-09-28 16:36:44.696428

,line_id,scheduled_arrival,estimated_arrival,trip_id,vehicle_id
192,1523,16:07:00,16:12:17,[VNWG3][LA77N]1523_0_1_1500_1529_0_1,1205
200,1523,16:32:00,16:33:53,[VNWG3][LA77N]1523_0_1_1530_1559_0_1,1913
201,1523,16:35:00,16:35:34,[VNWG3][LA77N]1523_0_2_1630_1659_0_1,1913
203,1604,16:39:00,16:36:35,[VNWG3][LA77N]1604_0_3_1600_1629_1_1,739
204,1607,16:42:00,16:41:48,[VNWG3][LA77N]1607_0_2_1600_1629_0_1,737
205,1607,16:49:00,16:43:34,[VNWG3][LA77N]1607_0_1_1630_1659_0_1,1721
206,1523,16:52:00,16:45:49,[VNWG3][LA77N]1523_0_1_1600_1629_0_1,1159
208,1120,16:56:00,16:46:00,[VNWG3][LA77N]1120_0_2_1630_1659_0_1,1298
209,1619,16:56:00,16:44:46,[VNWG3][LA77N]1619_0_1_1630_1659_0_1,1407
210,1607,17:07:00,16:50:44,[VNWG3][LA77N]1607_0_2_1630_1659_0_1,746
215,1529,17:18:00,17:02:10,[VNWG3][LA77N]1529_0_2_1600_1629_0_1,1247
217,1523,17:22:00,17:04:42,[VNWG3][LA77N]1523_0_1_1630_1659_0_1,1313

## let's see **stops**

In [9]:
stops = pd.DataFrame(requests.get(f"{api}/stops").json())
stops.head()

,district_id,district_name,facilities,id,lat,line_ids,locality_id,locality_name,lon,long_name,municipality_id,municipality_name,parish_id,parish_name,pattern_ids,route_ids,short_name,tts_name,wheelchair_boarding
0,11,None,[],7822,38.771331,[],022406,None,-9.097762,Av. D. João II,1106,None,110662,None,[],[],None,Av. D. João II,False
1,15,None,[],010001,38.754244,"[4001, 4002]",022857,None,-8.959557,Rua Carlos Manuel Rodrigues Francisco (Escola),1502,None,150201,None,"[4001_0_3, 4002_0_3]","[4001_0, 4002_0]",None,Rua Carlos Manuel Rodrigues Francisco ( Escola ),False
2,15,None,[],010002,38.754572,"[4001, 4002]",022857,None,-8.959615,R Carlos M. Francisco 229 (Escola Monte Novo),1502,None,150201,None,"[4001_0_3, 4002_0_3]","[4001_0, 4002_0]",None,Rua Carlos M. Francisco 229 ( Escola Monte Novo ),False
3,15,None,[],010005,38.754175,"[4001, 4002]",022857,None,-8.961806,ALCOCHETE (R CIPRIÃO FIGUEIREDO),1502,None,150201,None,"[4001_0_3, 4002_0_3]","[4001_0, 4002_0]",None,Alcochete ( Rua Ciprião Figueiredo ),False
4,15,None,[],010007,38.753196,"[4001, 4002]",022857,None,-8.963687,ALCOCHETE (R LEITE CUNHA) BIBLIOTECA,1502,None,150201,None,"[4001_0_3, 4002_0_3]","[4001_0, 4002_0]",None,Alcochete ( Rua Leite Cunha ) Biblioteca,False

In [10]:
stops.shape

(12752, 19)

In [11]:
stops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12752 entries, 0 to 12751
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   district_id          12752 non-null  object
 1   district_name        0 non-null      object
 2   facilities           12752 non-null  object
 3   id                   12752 non-null  object
 4   lat                  12752 non-null  float64
 5   line_ids             12752 non-null  object
 6   locality_id          11144 non-null  object
 7   locality_name        0 non-null      object
 8   lon                  12752 non-null  float64
 9   long_name            12752 non-null  object
 10  municipality_id      12752 non-null  object
 11  municipality_name    0 non-null      object
 12  parish_id            11997 non-null  object
 13  parish_name          0 non-null      object
 14  pattern_ids          12752 non-null  object
 15  route_ids            12752 non-null  object
 16  short_name           0 non-null      object
 17  tts_name             12752 non-null  object
 18  wheelchair_boarding  12752 non-null  bool
dtypes: bool(1), float64(2), object(16)
memory usage: 1.8+ MB

features with the name information do not even exist!!

In [12]:
# stops with no lines at all
no_lines = stops[stops["line_ids"].str.len() == 0]
print(len(no_lines))
no_lines.head()

376

,district_id,district_name,facilities,id,lat,line_ids,locality_id,locality_name,lon,long_name,municipality_id,municipality_name,parish_id,parish_name,pattern_ids,route_ids,short_name,tts_name,wheelchair_boarding
0,11,None,[],7822,38.771331,[],022406,None,-9.097762,Av. D. João II,1106,None,110662,None,[],[],None,Av. D. João II,False
10,15,None,[],010013,38.748733,[],022857,None,-8.966155,ALCOCHETE (R COOPERAÇÃO 27),1502,None,150201,None,[],[],None,Alcochete ( Rua Cooperação 27 ),False
11,15,None,[],010014,38.748700,[],022857,None,-8.965973,ALCOCHETE (R COOPERAÇÃO 27),1502,None,150201,None,[],[],None,Alcochete ( Rua Cooperação 27 ),False
30,15,None,[],010037,38.745522,[],None,None,-8.946050,PQ INDUSTRIAL BATEL (R ALFAZEMAS),1502,None,150201,None,[],[],None,Parque Industrial Batel ( Rua Alfazemas ),False
31,15,None,[],010038,38.745434,[],None,None,-8.945954,Rua das Alfazemas (X) Rua dos Alecrins,1502,None,150201,None,[],[],None,Cruzamento Entre ( Rua Das Alfazemas ) E Rua D...,False

## lets see **districts** and **municipalities** information

In [13]:
# district codes -> names
districts = pd.DataFrame(requests.get(f"{api}/locations/districts").json()["data"])
districts

    id                           name
0   01                         Aveiro
1   02                           Beja
2   03                          Braga
3   04                       Bragança
4   05                 Castelo Branco
5   06                        Coimbra
6   07                          Évora
7   08                           Faro
8   09                         Guarda
9   10                         Leiria
10  11                         Lisboa
11  12                     Portalegre
12  13                          Porto
13  14                       Santarém
14  15                        Setúbal
15  16               Viana do Castelo
16  17                      Vila Real
17  18                          Viseu
18  31      Ilha da Madeira (Madeira)
19  32  Ilha de Porto Santo (Madeira)
20  41            Ilha de Santa Maria
21  42             Ilha de São Miguel
22  43                  Ilha Terceira
23  44               Ilha da Graciosa
24  45              Ilha de São Jorge
25  46                   Ilha do Pico
26  47                  Ilha do Faial
27  48                Ilha das Flores
28  49                  Ilha do Corvo

In [14]:
districts.shape

(29, 2)

we have 29 districts!! so its not only about lisbon!!

In [15]:
# municipality codes -> names
municipalities = pd.DataFrame(requests.get(f"{api}/locations/municipalities").json()["data"])
municipalities.head(20)

   district_id    id                  name
0           01  0101                Águeda
1           01  0102    Albergaria-a-Velha
2           01  0103                Anadia
3           01  0104                Arouca
4           01  0105                Aveiro
5           01  0106      Castelo de Paiva
6           01  0107               Espinho
7           01  0108             Estarreja
8           01  0109  Santa Maria da Feira
9           01  0110                Ílhavo
10          01  0111              Mealhada
11          01  0112               Murtosa
12          01  0113   Oliveira de Azeméis
13          01  0114    Oliveira do Bairro
14          01  0115                  Ovar
15          01  0116   São João da Madeira
16          01  0117        Sever do Vouga
17          01  0118                 Vagos
18          01  0119        Vale de Cambra
19          02  0201             Aljustrel

In [16]:
municipalities.shape

(308, 3)

In [17]:
district_lisbon = municipalities['district_id'] == '11'  # lisbon
municipalities[district_lisbon]

    district_id    id                    name
147          11  1101                Alenquer
148          11  1102       Arruda dos Vinhos
149          11  1103                Azambuja
150          11  1104                 Cadaval
151          11  1105                 Cascais
152          11  1106                  Lisboa
153          11  1107                  Loures
154          11  1108                Lourinhã
155          11  1109                   Mafra
156          11  1110                  Oeiras
157          11  1111                  Sintra
158          11  1112  Sobral de Monte Agraço
159          11  1113           Torres Vedras
160          11  1114     Vila Franca de Xira
161          11  1115                 Amadora
162          11  1116                Odivelas

In [18]:
municipalities[district_lisbon].shape

(16, 3)

idea: focus only on lisbon (as expected!), bue the future dashboard must show everything

In [19]:
# which districts do the stops actually belong to
stops["district_id"].value_counts()

district_id
11    8348
15    4395
07       9
Name: count, dtype: int64

In [20]:
existing_districts = stops["district_id"].unique()
existing_districts = list(existing_districts)
existing_districts

['11', '15', '07']

In [21]:
district_ids = districts['id'].tolist()
for idd in existing_districts:
    if idd in district_ids:
        print(districts[districts['id'] == idd]['name'])

10    Lisboa
Name: name, dtype: object
14    Setúbal
Name: name, dtype: object
6    Évora
Name: name, dtype: object

In [22]:
# the 4 rows that have live info, next to the time right now
from datetime import datetime
print(datetime.now())

live = df[df["estimated_arrival"].notna()]
live[["line_id", "scheduled_arrival", "estimated_arrival", "trip_id", "vehicle_id"]]

2026-09-28 16:37:02.380776

,line_id,scheduled_arrival,estimated_arrival,trip_id,vehicle_id
192,1523,16:07:00,16:12:17,[VNWG3][LA77N]1523_0_1_1500_1529_0_1,1205
200,1523,16:32:00,16:33:53,[VNWG3][LA77N]1523_0_1_1530_1559_0_1,1913
201,1523,16:35:00,16:35:34,[VNWG3][LA77N]1523_0_2_1630_1659_0_1,1913
203,1604,16:39:00,16:36:35,[VNWG3][LA77N]1604_0_3_1600_1629_1_1,739
204,1607,16:42:00,16:41:48,[VNWG3][LA77N]1607_0_2_1600_1629_0_1,737
205,1607,16:49:00,16:43:34,[VNWG3][LA77N]1607_0_1_1630_1659_0_1,1721
206,1523,16:52:00,16:45:49,[VNWG3][LA77N]1523_0_1_1600_1629_0_1,1159
208,1120,16:56:00,16:46:00,[VNWG3][LA77N]1120_0_2_1630_1659_0_1,1298
209,1619,16:56:00,16:44:46,[VNWG3][LA77N]1619_0_1_1630_1659_0_1,1407
210,1607,17:07:00,16:50:44,[VNWG3][LA77N]1607_0_2_1630_1659_0_1,746
215,1529,17:18:00,17:02:10,[VNWG3][LA77N]1529_0_2_1600_1629_0_1,1247
217,1523,17:22:00,17:04:42,[VNWG3][LA77N]1523_0_1_1630_1659_0_1,1313

In [23]:
# which districts do the stops actually belong to
stops["district_id"].value_counts()

district_id
11    8348
15    4395
07       9
Name: count, dtype: int64

In [ ]:
stops[stops["district_id"] == "07"][["id", "long_name", "municipality_id", "line_ids"]]  # let's explore evora stops

,id,long_name,municipality_id,line_ids
12595,190002,LANDEIRA (PÇA REPUBLICA 12),0712,"[4901, 4902, 4906]"
12596,190003,LANDEIRA (R 25 ABRIL),0712,"[4901, 4902, 4906]"
12597,190004,LANDEIRA (R 25 ABRIL),0712,"[4901, 4902, 4906]"
12598,190005,BOMBEL,0712,"[4905, 4906]"
12599,190006,BOMBEL,0712,"[4905, 4906]"
12600,190007,VENDAS NOVAS (ESCOLA - AV 25 DE ABRIL),0712,"[4905, 4906]"
12601,190008,VENDAS NOVAS (ESCOLA - AV 25 DE ABRIL),0712,"[4905, 4906]"
12602,190025,Avenida da República (Frente Escola Prática),0712,"[4905, 4906]"
12603,190026,Avenida da República (Escola Prática),0712,"[4905, 4906]"

In [27]:
# call again and look at the ones that should have passed by now
r = requests.get(f"{api}/arrivals/by_stop/{stop_id}")
df = pd.DataFrame(r.json())

print(datetime.now())
print(df["observed_arrival"].notna().sum(), "rows with observed time")

df[df["trip_id"].notna()][["line_id", "scheduled_arrival", "estimated_arrival", "observed_arrival", "vehicle_id"]]

2026-09-28 16:40:00.964444
0 rows with observed time

    line_id scheduled_arrival estimated_arrival observed_arrival vehicle_id
192    1523          16:07:00          16:12:17             None       1205
200    1523          16:32:00          16:33:53             None       1913
204    1607          16:42:00          16:42:43             None        737
205    1607          16:49:00          16:45:06             None       1721
206    1523          16:52:00          16:46:10             None       1159
208    1120          16:56:00          16:49:19             None       1298
209    1619          16:56:00          16:47:46             None       1407
210    1607          17:07:00          16:56:13             None        746
215    1529          17:18:00          17:03:27             None       1247
217    1523          17:22:00          17:11:09             None       1313

## let's see **vehicles**

In [28]:
# all buses right now
vehicles = pd.DataFrame(requests.get(f"{api}/vehicles").json())
print(vehicles.shape)
vehicles.columns

(992, 34)

Index(['agency_id', 'bearing', 'bikes_allowed', 'block_id', 'capacity_seated',
       'capacity_standing', 'capacity_total', 'contactless', 'current_status',
       'direction_id', 'door_status', 'emission_class', 'event_id', 'id',
       'lat', 'license_plate', 'line_id', 'lon', 'make', 'model',
       'occupancy_estimated', 'occupancy_status', 'owner', 'pattern_id',
       'propulsion', 'registration_date', 'route_id', 'schedule_relationship',
       'shift_id', 'speed', 'stop_id', 'timestamp', 'trip_id',
       'wheelchair_accessible'],
      dtype='object')

In [ ]:
vehicles[vehicles["id"].str.contains("1298")]

,agency_id,bearing,bikes_allowed,block_id,capacity_seated,capacity_standing,capacity_total,contactless,current_status,direction_id,...,propulsion,registration_date,route_id,schedule_relationship,shift_id,speed,stop_id,timestamp,trip_id,wheelchair_accessible
704,41,268.0,False,None,0,0,0,True,STOPPED_AT,1,...,None,None,[LA77N]1120_0,SCHEDULED,None,1,120754,1790610054000,[VNWG3][LA77N]1120_0_2_1630_1659_0_1,None

In [30]:
# only the columns that matter for us, turned sideways so it's easier to read
cols = ["id", "line_id", "trip_id", "stop_id", "current_status", "timestamp", "speed", "lat", "lon"]
vehicles[vehicles["id"].str.contains("1298")][cols].T

                                                 704
id                                       [LA77N]1298
line_id                                         1120
trip_id         [VNWG3][LA77N]1120_0_2_1630_1659_0_1
stop_id                                       120754
current_status                            STOPPED_AT
timestamp                              1790610054000
speed                                              1
lat                                        38.697754
lon                                        -9.301336

In [31]:
# how many buses are actually doing a trip right now
print(vehicles["trip_id"].notna().sum(), "buses on a trip")
vehicles["current_status"].value_counts()

992 buses on a trip

current_status
IN_TRANSIT_TO    558
STOPPED_AT       270
INCOMING_AT      164
Name: count, dtype: int64

## mini experience: follow the bus

In [35]:
import time

bus = "1298"

# check the bus every 20 seconds, for 5 minutes
for i in range(15):
    v = pd.DataFrame(requests.get(f"{api}/vehicles").json())
    row = v[v["id"].str.contains(bus)].iloc[0]
    now = datetime.now().strftime("%H:%M:%S")
    print(now, row["stop_id"], row["current_status"], row["speed"])
    time.sleep(20)

16:47:21 120775 STOPPED_AT 1
16:47:41 120775 STOPPED_AT 4
16:48:01 120775 STOPPED_AT 3
16:48:21 120777 IN_TRANSIT_TO 0
16:48:41 120779 STOPPED_AT 0
16:49:01 120781 IN_TRANSIT_TO 25
16:49:21 120781 INCOMING_AT 0
16:49:42 120781 INCOMING_AT 0
16:50:02 120781 INCOMING_AT 0
16:50:22 120783 IN_TRANSIT_TO 2
16:50:42 120783 IN_TRANSIT_TO 2
16:51:02 120783 STOPPED_AT 11
16:51:22 120815 IN_TRANSIT_TO 12

KeyboardInterrupt:

In [44]:
# call every 5 seconds for 2 minutes and see how often the positions really change
last = None

for i in range(24):
    v = pd.DataFrame(requests.get(f"{api}/vehicles").json())
    newest = v["timestamp"].max()
    now = datetime.now().strftime("%H:%M:%S")

    changed = "new data" if newest != last else "same as before"
    print(now, newest, changed)

    last = newest
    time.sleep(5)

16:59:51 1790611179000 new data
16:59:56 1790611179000 same as before
17:00:01 1790611194000 new data
17:00:06 1790611194000 same as before
17:00:11 1790611199000 new data
17:00:16 1790611204000 new data
17:00:21 1790611204000 same as before
17:00:26 1790611214000 new data
17:00:31 1790611204000 new data
17:00:37 1790611225000 new data
17:00:42 1790611204000 new data
17:00:47 1790611235000 new data
17:00:52 1790611245000 new data
17:00:57 1790611250000 new data
17:01:02 1790611250000 same as before
17:01:07 1790611255000 new data
17:01:12 1790611260000 new data
17:01:18 1790611260000 same as before
17:01:23 1790611271000 new data
17:01:28 1790611281000 new data
17:01:33 1790611281000 same as before
17:01:39 1790611286000 new data
17:01:44 1790611291000 new data
17:01:49 1790611296000 new data

# summary of each available dataset

In [36]:
def summary(df):
    # one row per column: type, % empty, how many different values, one example
    return pd.DataFrame({
        "type": df.dtypes.astype(str),
        "empty_%": (df.isna().mean() * 100).round(1),
        "unique": df.astype(str).nunique(),
        "example": df.apply(lambda c: c.dropna().iloc[0] if c.notna().any() else None),
    })

In [ ]:
datasets = {
    "arrivals": df,
    "stops": stops,
    "vehicles": vehicles,
    "districts": districts,
    "municipalities": municipalities,
}

for name, data in datasets.items():
    print(f"{name} {data.shape}")
    print(summary(data))

arrivals (332, 14)
                           type  empty_%  unique  \
estimated_arrival        object     97.0      11
estimated_arrival_unix  float64     97.0      11
headsign                 object      0.0       9
line_id                  object      0.0       9
observed_arrival         object    100.0       1
observed_arrival_unix    object    100.0       1
pattern_id               object      0.0      12
related_trip_ids         object    100.0       1
route_id                 object      0.0      10
scheduled_arrival        object      0.0     297
scheduled_arrival_unix    int64      0.0     297
stop_sequence             int64      0.0      10
trip_id                  object     97.0      11
vehicle_id               object     97.0      11

                                                     example
estimated_arrival                                   16:12:17
estimated_arrival_unix                          1790608337.0
headsign                                Carcavelos (Estação)
line_id                                                 1604
observed_arrival                                        None
observed_arrival_unix                                   None
pattern_id                                   [LA77N]1604_0_3
related_trip_ids                                        None
route_id                                       [LA77N]1604_0
scheduled_arrival                                   05:56:00
scheduled_arrival_unix                            1790571360
stop_sequence                                             14
trip_id                 [VNWG3][LA77N]1523_0_1_1500_1529_0_1
vehicle_id                                              1205
stops (12752, 19)
                        type  empty_%  unique         example
district_id           object      0.0       3              11
district_name         object    100.0       1            None
facilities            object      0.0       1              []
id                    object      0.0   12752            7822
lat                  float64      0.0   12540       38.771331
line_ids              object      0.0    3286              []
locality_id           object     12.6     811          022406
locality_name         object    100.0       1            None
lon                  float64      0.0   12567       -9.097762
long_name             object      0.0    9169  Av. D. João II
municipality_id       object      0.0      23            1106
municipality_name     object    100.0       1            None
parish_id             object      5.9     116          110662
parish_name           object    100.0       1            None
pattern_ids           object      0.0    5078              []
route_ids             object      0.0    3722              []
short_name            object    100.0       1            None
tts_name              object      0.0    9100  Av. D. João II
wheelchair_boarding     bool      0.0       1           False
vehicles (992, 34)
                          type  empty_%  unique  \
agency_id               object      0.0       4
bearing                float64      3.6     332
bikes_allowed             bool      0.0       1
block_id                object    100.0       1
capacity_seated          int64      0.0       1
capacity_standing        int64      0.0       1
capacity_total           int64      0.0       1
contactless               bool      0.0       1
current_status          object      0.0       3
direction_id             int64      0.0       2
door_status             object      0.0       1
emission_class          object    100.0       1
event_id                object      0.0     992
id                      object      0.0     992
lat                    float64      0.0     980
license_plate           object    100.0       1
line_id                 object      0.0     454
lon                    float64      0.0     988
make                    object    100.0       1
model                   object    100.0       1
occupancy_estimated     object    100.0       1
occupancy_status        object      0.0       1
owner                   object    100.0       1
pattern_id              object      0.0     695
propulsion              object    100.0       1
registration_date       object    100.0       1
route_id                object      0.0     480
schedule_relationship   object      0.0       1
shift_id                object    100.0       1
speed                    int64      0.0      79
stop_id                 object      0.0     877
timestamp                int64      0.0      35
trip_id                 object      0.0     992
wheelchair_accessible   object    100.0       1

                                                                 example
agency_id                                                             41
bearing                                                            125.0
bikes_allowed                                                      False
block_id                                                            None
capacity_seated                                                        0
capacity_standing                                                      0
capacity_total                                                         0
contactless                                                         True
current_status                                                STOPPED_AT
direction_id                                                           1
door_status                                                       CLOSED
emission_class                                                      None
event_id               51ed53108b1b5ed71bd80602fd38207789c98aed981496...
id                                                           [LA77N]1321
lat                                                            38.710503
license_plate                                                       None
line_id                                                             1502
lon                                                            -9.238263
make                                                                None
model                                                               None
occupancy_estimated                                                 None
occupancy_status                                       NO_DATA_AVAILABLE
owner                                                               None
pattern_id                                        [VNWG3][LA77N]1502_0_2
propulsion                                                          None
registration_date                                                   None
route_id                                                   [LA77N]1502_0
schedule_relationship                                          SCHEDULED
shift_id                                                            None
speed                                                                 11
stop_id                                                           121057
timestamp                                                  1790610065000
trip_id                             [VNWG3][LA77N]1502_0_2_1600_1629_0_1
wheelchair_accessible                                               None
districts (29, 2)
        type  empty_%  unique example
id    object      0.0      29      01
name  object      0.0      29  Aveiro
municipalities (308, 3)
               type  empty_%  unique example
district_id  object      0.0      29      01
id           object      0.0     308    0101
name         object      0.0     307  Águeda

**vehicles**

* **keep**: id, agency_id, line_id, route_id, pattern_id, trip_id, direction_id,
      stop_id, current_status, timestamp, speed, bearing, lat, lon
* **drop** (always empty): block_id, shift_id, emission_class, license_plate, make, model,
      owner, propulsion, registration_date, wheelchair_accessible, occupancy_estimated
* **drop** (same value for every bus): capacity_*, bikes_allowed, contactless, door_status,
      occupancy_status
* **not sure**: schedule_relationship (always SCHEDULED now, but might change when a trip is cancelled),
      event_id (unique per row, could help remove duplicates)

**stops**

* **keep**: id, long_name, lat, lon, district_id, municipality_id, parish_id, locality_id, line_ids
* **drop** (always empty): district_name, municipality_name, parish_name, locality_name, short_name
* **drop** (no useful info): facilities, wheelchair_boarding
* **drop** (repeats another column): tts_name (same as long_name)
* **not sure**: pattern_ids, route_ids (the gtfs already has this, and better)

**arrivals**

* not useful at all
* we can know with vehicles df

**districts and municipalities**

* we want everything